const INCREMENTO = 'INCREMENTO';
const INCREMENTOIMPAR = 'INCREMENTOIMPAR';
const INCREMENTOASYNC = 'INCREMENTOASYNC';
const DECREMENTO = 'DECREMENTO';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOASYNC,
  INCREMENTOIMPAR
}